### ISSUE TITLE
simulation crashing on enable

### ISSUE THREAD

**Issue by IanSzalai** [IanSzalai/SuperSwerve#15]
```
Warning at edu.wpi.first.wpilibj.DriverStation.reportJoystickUnpluggedWarning(DriverStation.java:1489): Joystick Button 3 on port 0 not available, check if controller is plugged in
Error at frc.robot.commands.getInRangeOfTag.<init>(getInRangeOfTag.java:35): Unhandled exception: java.lang.NoSuchMethodError: 'double edu.wpi.first.math.Vector.dot(edu.wpi.first.math.Vector)'
        at edu.wpi.first.math.geometry.Quaternion.times(Quaternion.java:82)
        at edu.wpi.first.math.geometry.Translation3d.rotateBy(Translation3d.java:141)
        at edu.wpi.first.math.geometry.Transform3d.<init>(Transform3d.java:40)
        at frc.robot.commands.getInRangeOfTag.<init>(getInRangeOfTag.java:35)
        at frc.robot.RobotContainer.configureButtonBindings(RobotContainer.java:35)
        at frc.robot.RobotContainer.<init>(RobotContainer.java:28)
        at frc.robot.Robot.robotInit(Robot.java:38)
        at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:107)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:443)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
this only happens on my desktop computer and likely has something to do with the install of WPILIB. It is 2022.4.1. Build is fine

**Comment by alicekuznetsov** [comment]
It looks like its failing at this specific line in the Quaternion class since it can't find Vector.dot:
return new Quaternion(r1 * r2 - v1.dot(v2), v.get(0, 0), v.get(1, 0), v.get(2, 0));

This is kinda funny since I was literally looking for that method like, 2 days ago and couldn't find it so 
I haven't looked into it much yet, but it also fails on my laptop

**Comment by IanSzalai** [comment]
photonvision/wpilib bug, won't fix

**Comment by IanSzalai** [comment]
isn't happening to me anymore
