### ISSUE TITLE
code crashes when seeing april tag

### ISSUE THREAD

**Issue by IanSzalai** [IanSzalai/SuperSwerve#19]
any time an april tag is seen the code crashes
```
Unhandled exception: java.lang.RuntimeException: Cholesky decomposition failed! Input matrix:
Type = DDRM , rows = 3 , cols = 3
1.5000E-10 9.8567E-27 -1.9749E-20
9.8555E-27 1.5000E-10 -9.8752E-21
-1.9749E-20 -9.8752E-21 -2.8082E-12
Error at frc.robot.subsystems.Drivetrain.addVisionMeasurement(Drivetrain.java:290): Unhandled exception: java.lang.RuntimeException: Cholesky decomposition failed! Input matrix:
Type = DDRM , rows = 3 , cols = 3
1.5000E-10 9.8567E-27 -1.9749E-20
9.8555E-27 1.5000E-10 -9.8752E-21
-1.9749E-20 -9.8752E-21 -2.8082E-12
at edu.wpi.first.math.Matrix.lltDecompose(Matrix.java:576)
at edu.wpi.first.math.estimator.MerweScaledSigmaPoints.sigmaPoints(MerweScaledSigmaPoints.java:83)
at edu.wpi.first.math.estimator.UnscentedKalmanFilter.predict(UnscentedKalmanFilter.java:298)
at edu.wpi.first.math.estimator.KalmanFilterLatencyCompensator.applyPastGlobalMeasurement(KalmanFilterLatencyCompensator.java:148)
at edu.wpi.first.math.estimator.SwerveDrivePoseEstimator.addVisionMeasurement(SwerveDrivePoseEstimator.java:220)
at frc.robot.subsystems.Drivetrain.addVisionMeasurement(Drivetrain.java:290)
at frc.robot.commands.UpdatePoseEstimator.execute(UpdatePoseEstimator.java:52)
at edu.wpi.first.wpilibj2.command.CommandScheduler.run(CommandScheduler.java:280)
at frc.robot.Robot.robotPeriodic(Robot.java:70)
at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:328)
at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:131)
at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:463)
at frc.robot.Main.main(Main.java:23)
The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
See https://wpilib.org/stacktrace for more information.
Warning at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:388): The robot program quit unexpectedly. This is usually due to a code error.
The startCompetition() method (or methods called by it) should have handled the exception above.
```

**Comment by IanSzalai** [comment]
"That’s been fixed in WPILib 2023 (not released until kickoff)."
https://www.chiefdelphi.com/t/photonvision-beta-2023-apriltags/415626/305
